### ISSUE TITLE
Enderman crashing server

### ISSUE THREAD

**Issue by GatitoUwU** [MultiPaper/ShreddedPaper#11]
### Stack trace

2:27] [ShreddedPaperTickThread-12/ERROR]: ShreddedPaperTickThread-12 tried to run a task from the wrong thread: Cannot move entity off-main
[23:02:27] [ShreddedPaperTickThread-12/ERROR]: Extra data: entity=EnderMan['Enderman'/225979, uuid='c0c3fb3a-231f-4580-8a86-16feb121c694', l='ServerLevel[world]', x=-132405.76, y=84.00, z=52609.68, cpos=[-8276, 3288], tl=36, v=true]
[23:02:27] [ShreddedPaperTickThread-12/ERROR]: Server Version: 1.20.6-80-91b8126 (MC: 1.20.6)
[23:02:27] [ShreddedPaperTickThread-12/ERROR]: Region locks currently held (regionSize=8 chunks): [world=[[-1035,408], [-1034,408], [-1034,410], [-1036,408], [-1035,410], [-1036,410], [-1036,409], [-1034,409], [-1035,409]]]
[23:02:27] [ShreddedPaperTickThread-12/ERROR]: Stack trace:
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.failedTickThreadCheck(TickThread.java:57) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:115) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.papermc.paper.chunk.system.entity.EntityLookup.moveEntity(EntityLookup.java:498) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.papermc.paper.chunk.system.entity.EntityLookup$EntityCallback.onMove(EntityLookup.java:876) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:4843) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Entity.setPos(Entity.java:872) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.LivingEntity.randomTeleport(LivingEntity.java:4305) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.LivingEntity.randomTeleport(LivingEntity.java:4272) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.monster.EnderMan.teleport(EnderMan.java:360) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.monster.EnderMan.teleport(EnderMan.java:329) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.monster.EnderMan.hurt(EnderMan.java:435) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3580) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:748) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.monster.EnderMan.aiStep(EnderMan.java:301) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3183) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Mob.tick(Mob.java:474) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1491) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1363) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperEntityTicker.tickEntity(ShreddedPaperEntityTicker.java:31) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.region.LevelChunkRegion.forEachTickingEntity(LevelChunkRegion.java:68) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker._tickRegion(ShreddedPaperChunkTicker.java:93) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$tickRegion$1(ShreddedPaperChunkTicker.java:49) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$run$6(ShreddedPaperRegionScheduler.java:123) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.lambda$tryLockNow$3(ShreddedPaperRegionLocker.java:111) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryReadOnlyLockNow(ShreddedPaperRegionLocker.java:156) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryLockNow(ShreddedPaperRegionLocker.java:105) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.run(ShreddedPaperRegionScheduler.java:122) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$createTask$5(ShreddedPaperRegionScheduler.java:114) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[23:02:27] [ShreddedPaperTickThread-12/ERROR]: Entity threw exception at world:-132405.75686926488,84.0,52609.678054515636
java.lang.IllegalStateException: Cannot move entity off-main
	at io.papermc.paper.util.TickThread.failedTickThreadCheck(TickThread.java:58) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:115) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.papermc.paper.chunk.system.entity.EntityLookup.moveEntity(EntityLookup.java:498) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.papermc.paper.chunk.system.entity.EntityLookup$EntityCallback.onMove(EntityLookup.java:876) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:4843) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Entity.setPos(Entity.java:872) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.LivingEntity.randomTeleport(LivingEntity.java:4305) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.LivingEntity.randomTeleport(LivingEntity.java:4272) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.monster.EnderMan.teleport(EnderMan.java:360) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.monster.EnderMan.teleport(EnderMan.java:329) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.monster.EnderMan.hurt(EnderMan.java:435) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3580) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:748) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.monster.EnderMan.aiStep(EnderMan.java:301) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3183) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Mob.tick(Mob.java:474) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1491) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1363) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperEntityTicker.tickEntity(ShreddedPaperEntityTicker.java:31) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.region.LevelChunkRegion.forEachTickingEntity(LevelChunkRegion.java:68) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker._tickRegion(ShreddedPaperChunkTicker.java:93) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$tickRegion$1(ShreddedPaperChunkTicker.java:49) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$run$6(ShreddedPaperRegionScheduler.java:123) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.lambda$tryLockNow$3(ShreddedPaperRegionLocker.java:111) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryReadOnlyLockNow(ShreddedPaperRegionLocker.java:156) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryLockNow(ShreddedPaperRegionLocker.java:105) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.run(ShreddedPaperRegionScheduler.java:122) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$createTask$5(ShreddedPaperRegionScheduler.java:114) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[23:02:27] [ShreddedPaperTickThread-12/ERROR]: ShreddedPaperTickThread-12 tried to run a task from the wrong thread: Cannot remove entity off-main
[23:02:27] [ShreddedPaperTickThread-12/ERROR]: Extra data: entity=EnderMan['Enderman'/225979, uuid='c0c3fb3a-231f-4580-8a86-16feb121c694', l='ServerLevel[world]', x=-132405.76, y=84.00, z=52609.68, cpos=[-8276, 3288], tl=36, v=true]
[23:02:27] [ShreddedPaperTickThread-12/ERROR]: Server Version: 1.20.6-80-91b8126 (MC: 1.20.6)
[23:02:27] [ShreddedPaperTickThread-12/ERROR]: Region locks currently held (regionSize=8 chunks): [world=[[-1035,408], [-1034,408], [-1034,410], [-1036,408], [-1035,410], [-1036,410], [-1036,409], [-1034,409], [-1035,409]]]
[23:02:27] [ShreddedPaperTickThread-12/ERROR]: Stack trace:
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.failedTickThreadCheck(TickThread.java:57) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:115) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4947) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Entity.remove(Entity.java:794) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.LivingEntity.remove(LivingEntity.java:803) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Entity.discard(Entity.java:729) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1371) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperEntityTicker.tickEntity(ShreddedPaperEntityTicker.java:31) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.region.LevelChunkRegion.forEachTickingEntity(LevelChunkRegion.java:68) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker._tickRegion(ShreddedPaperChunkTicker.java:93) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$tickRegion$1(ShreddedPaperChunkTicker.java:49) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$run$6(ShreddedPaperRegionScheduler.java:123) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.lambda$tryLockNow$3(ShreddedPaperRegionLocker.java:111) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryReadOnlyLockNow(ShreddedPaperRegionLocker.java:156) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryLockNow(ShreddedPaperRegionLocker.java:105) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.run(ShreddedPaperRegionScheduler.java:122) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$createTask$5(ShreddedPaperRegionScheduler.java:114) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[23:02:27] [ShreddedPaperTickThread-12/ERROR]: [ShreddedPaperChunkTicker] Exception ticking region RegionPos[-1035, 409]
java.lang.IllegalStateException: Cannot remove entity off-main
	at io.papermc.paper.util.TickThread.failedTickThreadCheck(TickThread.java:58) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:115) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4947) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Entity.remove(Entity.java:794) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.LivingEntity.remove(LivingEntity.java:803) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Entity.discard(Entity.java:729) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1371) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperEntityTicker.tickEntity(ShreddedPaperEntityTicker.java:31) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.region.LevelChunkRegion.forEachTickingEntity(LevelChunkRegion.java:68) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker._tickRegion(ShreddedPaperChunkTicker.java:93) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$tickRegion$1(ShreddedPaperChunkTicker.java:49) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$run$6(ShreddedPaperRegionScheduler.java:123) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.lambda$tryLockNow$3(ShreddedPaperRegionLocker.java:111) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryReadOnlyLockNow(ShreddedPaperRegionLocker.java:156) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryLockNow(ShreddedPaperRegionLocker.java:105) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.run(ShreddedPaperRegionScheduler.java:122) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$createTask$5(ShreddedPaperRegionScheduler.java:114) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[23:02:27] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Ticking thread crash while ticking region RegionPos[-1035, 409]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$tickRegion$2(ShreddedPaperChunkTicker.java:51) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194) ~[?:?]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.run(ShreddedPaperRegionScheduler.java:130) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$createTask$5(ShreddedPaperRegionScheduler.java:114) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Cannot remove entity off-main
	at io.papermc.paper.util.TickThread.failedTickThreadCheck(TickThread.java:58) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:115) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4947) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Entity.remove(Entity.java:794) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.LivingEntity.remove(LivingEntity.java:803) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.entity.Entity.discard(Entity.java:729) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1371) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperEntityTicker.tickEntity(ShreddedPaperEntityTicker.java:31) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.region.LevelChunkRegion.forEachTickingEntity(LevelChunkRegion.java:68) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker._tickRegion(ShreddedPaperChunkTicker.java:93) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$tickRegion$1(ShreddedPaperChunkTicker.java:49) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$run$6(ShreddedPaperRegionScheduler.java:123) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.lambda$tryLockNow$3(ShreddedPaperRegionLocker.java:111) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryReadOnlyLockNow(ShreddedPaperRegionLocker.java:156) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryLockNow(ShreddedPaperRegionLocker.java:105) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.run(ShreddedPaperRegionScheduler.java:122) ~[shreddedpaper-1.20.6.jar:1.20.6-80-91b8126]
	... 7 more

### Plugin and Datapack List

[23:14:25 INFO]: Bukkit Plugins: (11):
[23:14:25 INFO]:  - ⁺Broadcast, *⁺DisableJoinMessage, ⁺LuckPerms, ⁺Midnight, NoChatReports, ⁺PlaceholderAPI, ProtocolLib, ⁺PureServerUtils, ⁺spark, ⁺Vault
[23:14:25 INFO]:  voicechat

### Actions to reproduce (if known)

I've nothing, it crashed randomly

### ShreddedPaper version

[23:14:57 INFO]: Checking version, please wait...
[23:14:58 INFO]: Current ShreddedPaper Version: 1.20.6-80-91b8126 (MC: 1.20.6)*
* You are running the latest version
Previous: MultiPaper-1.20.1-50 (MC: 1.20.1)

**Comment by PureGero** [comment]
Fixed now, thank you for finding this bug!
