### ISSUE TITLE
Incompatibility with liberty bans plugin

### ISSUE THREAD

**Issue by TofaDev** [MultiPaper/ShreddedPaper#13]
### Expected behavior

launching the [libertybans ](https://github.com/A248/LibertyBans)plugin without errors

### Observed/Actual behavior

When starting the server, I get the following error from the plugin:

`[11:41:01 ERROR]: Error occurred while enabling LibertyBans v1.1.0-RC2 (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean org.bukkit.Server.isGlobalTickThread()'
        at LibertyBans-ClassLoader/space.arim.morepaperlib.scheduling.GracefulScheduling.isOnGlobalRegionThread(GracefulScheduling.java:146) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.api.env.bukkit.BukkitFactoryOfTheFutureImpl.isPrimaryThread0(BukkitFactoryOfTheFutureImpl.java:59) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.api.env.concurrent.MainThreadCachingFutureFactory.isPrimaryThread(MainThreadCachingFutureFactory.java:49) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.api.env.bukkit.BukkitFactoryOfTheFutureImpl.create(BukkitFactoryOfTheFutureImpl.java:53) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.api.env.bukkit.BukkitFactoryOfTheFuture.create(BukkitFactoryOfTheFuture.java:56) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.api.env.bukkit.BukkitFactoryOfTheFuture.create(BukkitFactoryOfTheFuture.java:45) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.api.env.bukkit.BukkitPlatformHandleImpl.createFuturesFactory(BukkitPlatformHandle.java:64) ~[LibertyBans-ClassLoader:?]
        at java.base/java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
        at LibertyBans-ClassLoader/space.arim.libertybans.core.service.StandardAsynchronicityManager.startup(StandardAsynchronicityManager.java:90) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.libertybans.core.LifecycleGodfather.startup0(LifecycleGodfather.java:75) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.libertybans.core.AbstractBaseFoundation.timedEvent(AbstractBaseFoundation.java:126) ~[LibertyBans-ClassLoader:?]
        at LibertyBans-ClassLoader/space.arim.libertybans.core.AbstractBaseFoundation.startup(AbstractBaseFoundation.java:64) ~[LibertyBans-ClassLoader:?]
        at LibertyBans_Release-1.1.0-RC2.jar/space.arim.libertybans.env.spigot.plugin.SpigotPlugin.initialize(SpigotPlugin.java:112) ~[LibertyBans_Release-1.1.0-RC2.jar:?]
        at LibertyBans_Release-1.1.0-RC2.jar/space.arim.libertybans.env.spigot.plugin.SpigotPlugin.onEnable(SpigotPlugin.java:48) ~[LibertyBans_Release-1.1.0-RC2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[shreddedpaper-1.20.6.jar:1.20.6-92-7aa6d7c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[shreddedpaper-1.20.6.jar:1.20.6-92-7aa6d7c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:645) ~[shreddedpaper-1.20.6.jar:1.20.6-92-7aa6d7c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:593) ~[shreddedpaper-1.20.6.jar:1.20.6-92-7aa6d7c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:684) ~[shreddedpaper-1.20.6.jar:1.20.6-92-7aa6d7c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:446) ~[shreddedpaper-1.20.6.jar:1.20.6-92-7aa6d7c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361) ~[shreddedpaper-1.20.6.jar:1.20.6-92-7aa6d7c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1159) ~[shreddedpaper-1.20.6.jar:1.20.6-92-7aa6d7c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[shreddedpaper-1.20.6.jar:1.20.6-92-7aa6d7c]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[11:41:01 INFO]: [LibertyBans] Disabling LibertyBans v1.1.0-RC2`

### Steps/models to reproduce

1. put the plugin in the plugins folder
2. started the server core

### Plugin and Datapack List

plugins: 

Bukkit Plugins: (32):
-  ⁺AbstractMenus, ajLeaderboards, ⁺AntiRelog, ⁺AuctionHouse, Chatty, ⁺DecentHolograms, *⁺DonateBench, ⁺DonateCase, *⁺HideStream, LibertyBans,  ⁺LuckPerms, ⁺PEconomy, ⁺PlaceholderAPI, ⁺PlayerKits2, ⁺ProtectionStones, ProtocolLib, Quests, ⁺RHLeafDecay, ⁺SimpleTpa, SkinsRestorer,  ⁺SKLibrary, ⁺spark, TAB-Bridge, ⁺VanilliumGUI, ⁺Vault, ⁺VCC, ViaBackwards, ViaRewind, ViaVersion, ⁺WorldEdit,  ⁺WorldGuard, ⁺WorldGUI

datapacks: missing

### ShreddedPaper version

1.20.6-92-7aa6d7c (MC: 1.20.6)

**Comment by PureGero** [comment]
Fixed now, thank you for finding and reporting this issue!
