### ISSUE TITLE
If /gamerule spawnRadius is larger than region size, players can't respawn

### ISSUE THREAD

**Issue by PureGero** [MultiPaper/ShreddedPaper#14]
### Stack trace

```
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.failedTickThreadCheck(TickThread.java:57) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:262) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at net.minecraft.world.level.Level.getChunk(Level.java:937) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at net.minecraft.world.level.Level.getChunk(Level.java:876) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at net.minecraft.server.level.PlayerRespawnLogic.getOverworldRespawnPos(PlayerRespawnLogic.java:19) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at net.minecraft.server.level.ServerPlayer.getSpawnPoint(ServerPlayer.java:499) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at net.minecraft.server.players.PlayerList.respawnAsyncGetRespawnPosition(PlayerList.java:972) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at net.minecraft.server.players.PlayerList.lambda$respawnAsync$5(PlayerList.java:866) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$runOnMany$9(ShreddedPaperRegionScheduler.java:150) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.lambda$tryLockNow$3(ShreddedPaperRegionLocker.java:111) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryReadOnlyLockNow(ShreddedPaperRegionLocker.java:156) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryLockNow(ShreddedPaperRegionLocker.java:105) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$runOnMany$8(ShreddedPaperRegionScheduler.java:142) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.lambda$tryLockNow$3(ShreddedPaperRegionLocker.java:111) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryReadOnlyLockNow(ShreddedPaperRegionLocker.java:156) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryLockNow(ShreddedPaperRegionLocker.java:105) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$runOnMany$8(ShreddedPaperRegionScheduler.java:142) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.runOnMany(ShreddedPaperRegionScheduler.java:157) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$scheduleOnMany$3(ShreddedPaperRegionScheduler.java:42) ~[shreddedpaper-1.20.6.jar:1.20.6-DEV-0224122]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Plugin and Datapack List

Nil

### Actions to reproduce (if known)

1. /gamerule spawnRadius 5000
2. Die and respawn

### ShreddedPaper version

Nil

**Comment by PureGero** [comment]
Fixed in 1.21.11
