### ISSUE TITLE
Incompatibility with spawn plugin

### ISSUE THREAD

**Issue by TofaDev** [MultiPaper/ShreddedPaper#16]
### Expected behavior

i'll be teleported to server spawn

### Observed/Actual behavior

i get a message like a "unhandled error while executing command" in [spawn plugin](https://github.com/rockquiet/Spawn)

error: 

```
10:04:32 ERROR]: ShreddedPaperTickThread-1 tried to run a task from the wrong thread: Can't move entity to async destination
[10:04:32 ERROR]: Extra data: world=world, x=-3737 y=? z=3113
[10:04:32 ERROR]: Server Version: 1.20.6-96-1e763bd (MC: 1.20.6)
[10:04:32 ERROR]: Region locks currently held (regionSize=8 chunks): [world=[[-35,31], [-34,30], [-35,30], [-33,32], [-34,32], [-34,31], [-33,31], [-35,32], [-33,30]]]
[10:04:32 ERROR]: Stack trace:
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.failedTickThreadCheck(TickThread.java:57) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:127) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.world.entity.Entity.moveTo(Entity.java:2155) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.internalTeleport(ServerGamePacketListenerImpl.java:1841) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1496) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1355) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at Spawn-2.4.1.jar/me.rockquiet.spawn.SpawnHandler.teleportPlayer(SpawnHandler.java:103) ~[Spawn-2.4.1.jar:?]
        at Spawn-2.4.1.jar/me.rockquiet.spawn.commands.SpawnCommand.onCommand(SpawnCommand.java:69) ~[Spawn-2.4.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.lambda$run$0(BukkitCommandNode.java:95) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.SynchronousPluginExecution.execute(SynchronousPluginExecution.java:70) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.SynchronousPluginExecution.executeNoException(SynchronousPluginExecution.java:37) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:97) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:456) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:363) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2286) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2260) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tryHandleChat(ServerGamePacketListenerImpl.java:2426) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChatCommand(ServerGamePacketListenerImpl.java:2254) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.handle(ServerboundChatCommandPacket.java:28) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.handle(ServerboundChatCommandPacket.java:14) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:58) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.ShreddedPaper.lambda$runSync$0(ShreddedPaper.java:21) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:177) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$_tickRegion$3(ShreddedPaperChunkTicker.java:80) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.region.LevelChunkRegion.forEachTickingEntity(LevelChunkRegion.java:77) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker._tickRegion(ShreddedPaperChunkTicker.java:77) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$tickRegion$1(ShreddedPaperChunkTicker.java:49) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$run$6(ShreddedPaperRegionScheduler.java:123) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.lambda$tryLockNow$3(ShreddedPaperRegionLocker.java:111) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryReadOnlyLockNow(ShreddedPaperRegionLocker.java:156) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryLockNow(ShreddedPaperRegionLocker.java:105) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.run(ShreddedPaperRegionScheduler.java:122) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$createTask$5(ShreddedPaperRegionScheduler.java:114) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[10:04:32 ERROR]: Command exception: /spawn
org.bukkit.command.CommandException: Unhandled exception executing command 'spawn' in plugin Spawn v2.4.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.lambda$run$0(BukkitCommandNode.java:95) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.SynchronousPluginExecution.execute(SynchronousPluginExecution.java:70) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.SynchronousPluginExecution.executeNoException(SynchronousPluginExecution.java:37) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:97) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:456) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:363) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2286) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2260) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tryHandleChat(ServerGamePacketListenerImpl.java:2426) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChatCommand(ServerGamePacketListenerImpl.java:2254) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.handle(ServerboundChatCommandPacket.java:28) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.handle(ServerboundChatCommandPacket.java:14) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:58) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.ShreddedPaper.lambda$runSync$0(ShreddedPaper.java:21) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:177) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$_tickRegion$3(ShreddedPaperChunkTicker.java:80) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.region.LevelChunkRegion.forEachTickingEntity(LevelChunkRegion.java:77) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker._tickRegion(ShreddedPaperChunkTicker.java:77) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$tickRegion$1(ShreddedPaperChunkTicker.java:49) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$run$6(ShreddedPaperRegionScheduler.java:123) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.lambda$tryLockNow$3(ShreddedPaperRegionLocker.java:111) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryReadOnlyLockNow(ShreddedPaperRegionLocker.java:156) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryLockNow(ShreddedPaperRegionLocker.java:105) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.run(ShreddedPaperRegionScheduler.java:122) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$createTask$5(ShreddedPaperRegionScheduler.java:114) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.IllegalStateException: Can't move entity to async destination
        at io.papermc.paper.util.TickThread.failedTickThreadCheck(TickThread.java:58) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:127) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.world.entity.Entity.moveTo(Entity.java:2155) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.internalTeleport(ServerGamePacketListenerImpl.java:1841) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1496) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1355) ~[shreddedpaper-1.20.6.jar:1.20.6-96-1e763bd]
        at Spawn-2.4.1.jar/me.rockquiet.spawn.SpawnHandler.teleportPlayer(SpawnHandler.java:103) ~[Spawn-2.4.1.jar:?]
        at Spawn-2.4.1.jar/me.rockquiet.spawn.commands.SpawnCommand.onCommand(SpawnCommand.java:69) ~[Spawn-2.4.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 39 more
```

### Steps/models to reproduce

1. set up the plugin
2. get away from the spawn point by ~1000 blocks
3. write the command "/spawn"

### Plugin and Datapack List

```
[10:06:49 INFO]: Bukkit Plugins: (33):
[10:06:49 INFO]:  - ⁺AbstractMenus, ajLeaderboards, ⁺AntiRelog, BetterRTP, Chatty, ⁺CrazyAuctions, ⁺DecentHolograms, ⁺DonateCase, *⁺HideStream, LibertyBans
[10:06:49 INFO]:  ⁺LuckPerms, ⁺MoneyFromMobs, ⁺PEconomy, ⁺PlaceholderAPI, Plan, ⁺PlayerKits2, ⁺ProtectionStones, ProtocolLib, ⁺PvPToggle, Quests
[10:06:49 INFO]:  ⁺RHLeafDecay, ⁺SimpleHomes, ⁺SimpleTpa, SkinsRestorer, ⁺SKLibrary, ⁺spark, ⁺Spawn, TAB-Bridge, ⁺VanilliumLiteFeatures, ⁺Vault
[10:06:49 INFO]:  ⁺WorldEdit, ⁺WorldGuard, ⁺WorldGUI
```

### ShreddedPaper version

 1.20.6-96-1e763bd

**Comment by ProdPreva1l** [comment]
Not a shreddedpaper issue, they are not doing an async teleport.

**Comment by PsychooYT** [comment]
Just use essentialsspawn & essentials
